DefaultContentLanguage = "jp"
baseURL = "https://tagging.jp"
disableLanguages = ["En", "Fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Tagging | バーコード商品管理"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.en.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.en.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.en.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "project"
name = "Project"
weight = 3
[[Languages.en.menu.main]]
URL = "service"
name = "Service"
weight = 4
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.en.menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[Languages.en.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.fr.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.fr.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.fr.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.fr.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 2
[[Languages.fr.menu.main]]
URL = "project"
name = "Projet"
weight = 3
[[Languages.fr.menu.main]]
URL = "service"
name = "Un service"
weight = 4
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[Languages.fr.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Tarification"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[Languages.jp]
contentDir = "content/japanese"
copyright = "Copyright &copy; 2020 [Satis](https://satis-corp.com) All Rights Reserved <br>Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "ja-JP"
languageName = "Jp"
weight = 1
[[Languages.jp.menu.footer]]
URL = "https://tagging.jp/about"
name = "About"
weight = 1
[[Languages.jp.menu.footer]]
URL = "https://tagging.jp/pricing"
name = "Pricing"
weight = 2
[[Languages.jp.menu.footer]]
URL = "https://tagging.jp/faq"
name = "FAQ"
weight = 3
[[Languages.jp.menu.footer]]
URL = "https://tagging.jp/supply"
name = "Supply"
weight = 4
[[Languages.jp.menu.footer]]
URL = "https://tagging.jp/service"
name = "Tag"
weight = 5
[[Languages.jp.menu.footer]]
URL = "https://tagging.netlify.app/contact/"
name = "Contact"
weight = 6
[[Languages.jp.menu.main]]
URL = "https://tagging.jp/"
name = "Home"
weight = 1
[[Languages.jp.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.jp.menu.main]]
URL = "pricing"
name = "Pricing"
weight = 3
[[Languages.jp.menu.main]]
URL = "faq"
name = "FAQ"
weight = 4
[[Languages.jp.menu.main]]
URL = "supply"
name = "Supply"
weight = 5
[[Languages.jp.menu.main]]
URL = "service"
name = "Tag"
weight = 6
[[Languages.jp.menu.main]]
URL = "https://tagging.netlify.app/contact/"
name = "Contact"
weight = 7
[[Languages.jp.menu.main]]
URL = "ec"
name = "EC"
weight = 8
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Satis"
contact_form_action = "#"
description = "商品管理,タグ管理,バーコード管理,中古買取"
email = "satis@satis-corp.com"
google_analitycs_id = ""
location = "千葉県船橋市宮本1-7-1 203号"
logo = "images/logo.png"
mobile = "047-427-4878"
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "35.700060"
map_longitude = "139.992249"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap.3.4.1/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/all.min.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap.3.4.1/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "fab fa-line"
link = "https://lin.ee/y2ZidQj"
[[params.social]]
icon = "fab fa-slack"
link = "https://join.slack.com/t/thesatis/shared_invite/enQtOTY5MDA4NjY2Njc2LTU4NjllMWUxYzU4MDExYTc3NDI1ZDU4NjE1Njc4MjViZDIzNjM2MjBlZDFiYmJhNTE0MjRlNWQzMTI2YmE5OWM"
[services.googleAnalytics]
id = "UA-82065033-4"
